name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  project:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Configure and build
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
